#!/bin/sh
#
# ifdown hook script to disable port forwarding

case "$IFACE" in
  {{posm_netif}}) exit 0 ;;
esac

iptables -t nat -D POSTROUTING -o $IFACE -j MASQUERADE
iptables -D FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -D FORWARD -i {{posm_netif}} -o $IFACE -j ACCEPT
