#!/bin/bash

posm_env=production

# network
posm_network="172.16" # class B
posm_wlan_subnet="$posm_network.1"
posm_lan_subnet="$posm_network.2"
posm_wlan_ip="$posm_wlan_subnet.1"
posm_lan_ip="$posm_lan_subnet.1"
posm_wan_netif="eth0"
posm_lan_netif=""
posm_wlan_netif="wlan0"
posm_ssid="POSM"
posm_wpa_passphrase="awesomeposm" # 8..63 characters
posm_wifi_channel="1"
posm_wifi_80211n="1" # set to 0 to disable 802.11n
posm_wifi_wpa="2" # set to 0 to disable passwords
posm_hostname="posm"
posm_domain="io"
lan_domain="lan"
posm_fqdn="${posm_hostname}.${posm_domain}"
osm_fqdn="osm.${posm_fqdn}"

# urls
protocol="https"
posm_base_url="${protocol}://${posm_fqdn}"
osm_base_url="${protocol}://${osm_fqdn}"
fp_api_base_url="${posm_base_url}/fp"
fp_tile_base_url="${posm_base_url}/fp-tiler"

# ports
fp_tiler_port=8080
fp_tasks_port=8081
fp_web_port=3000
tessera_port=8082
omk_server_port=3210
posm_admin_port=3211
osm_web_port=9000
cgimap_port=54321

# web
# auth=true # uncomment this to enable web authentication
auth_user=POSM
auth_password=awesomeposm

# field papers
fp_secret_key_base=redacted
fp_mapzen_search_key=redacted

# osm
osm_posm_user="POSM"
osm_posm_description="Portable OpenStreetMap"

# databases
mysql_pw=posm
mysql_size=small
osm_pg_owner="osm"
osm_pg_pass="openstreetmap"
osm_pg_dbname="osm"
osm_carto_pg_dbname="gis"
osm_carto_pg_temp_dbname="gis_temp"
osm_carto_pg_owner="gis"
osm_carto_pg_users="root fp omk"
osm_carto_pg_pass="openstreetmap"

# tile styles [posm, osm]
carto_styles="posm"

# data
demo_data_pbf="http://download.geofabrik.de/south-america/ecuador-latest.osm.pbf"
#osm2pg_style="https://raw.githubusercontent.com/openstreetmap/osm2pgsql/0.88.1/empty.style"
osm2pg_opt="--create --hstore-all --hstore-add-index --extra-attributes --slim --drop --unlogged"
