#!/bin/bash

posm_env=production

# network
posm_subnet="192.168.6" # always a Class-C /24
posm_ip="$posm_subnet.1"
posm_wan_netif="p2p1"
posm_netif="wlan0"
posm_ssid="posm"
posm_wpa_passphrase="awesomeposm" # 8..63 characters
posm_wifi_channel="1"
posm_domain="lan"
posm_hostname="posm.$posm_domain"

# urls
posm_base_url="http://${posm_hostname}"
fp_api_base_url="${posm_base_url}/fp"
fp_tile_base_url="${posm_base_url}/fp-tiler"

# ports
fp_tiler_port=8080
fp_tasks_port=8081
fp_web_port=3000
tessera_port=8082
omk_server_port=3210
macrocosm_api_port=4000

# field papers
fp_secret_key_base=redacted

# tile server (tessera)
map_style="https://gist.githubusercontent.com/jflemer-ndp/a9c4ff93cf6a9a4121e7/raw/project.xml"
tessera_uri="mapnik://./project.xml"

# databases
mysql_pw=posm
mysql_size=small
pgsql_ver=9.3
postgis_ver=2.1
osm_pg_dbname="gis"
osm_pg_owner="gis"
osm_pg_users="root fp omk"
macrocosm_pg_owner="macrocosm"
macrocosm_pg_pass="macrocosm"

node_ver=5

# data
demo_data_pbf="http://download.geofabrik.de/south-america/ecuador-latest.osm.pbf"
#osm2pg_style="https://raw.githubusercontent.com/openstreetmap/osm2pgsql/0.88.1/empty.style"
osm2pg_opt="--create --hstore-all --hstore-add-index --extra-attributes --slim --drop --unlogged"
