#!/bin/bash

posm_env=production

# network
# class B
posm_network="172.16"
posm_wlan_subnet="172.16.1"
posm_lan_subnet="172.16.2"
posm_wlan_ip="172.16.1.1"
posm_lan_ip="172.16.2.1"
# first ethernet interface
posm_wan_netif="$(find /sys/class/net/ -name en* -printf '%f\n' | head -1)"
# second ethernet interface (if present)
posm_lan_netif="$(find /sys/class/net -name en* -printf '%f\n' | tail -n +2)"
# first wireless interface
posm_wlan_netif="$(find /sys/class/net/ -name wl* -printf '%f\n' | head -1)"
posm_ssid="POSM"
# 8..63 characters
posm_wpa_passphrase="awesomeposm"
posm_wifi_channel="1"
# set to 0 to disable 802.11n
posm_wifi_80211n="1"
# set to 0 to disable passwords
posm_wifi_wpa="2"
posm_hostname="posm"
posm_domain="io"
lan_domain="lan"
posm_fqdn="posm.io"
osm_fqdn="osm.${posm_fqdn}"
webodm_fqdn="webodm.${posm_fqdn}"

# urls
posm_base_url="http://${posm_fqdn}"
osm_base_url="http://${osm_fqdn}"
fp_api_base_url="${posm_base_url}/fp"
fp_tile_base_url="${posm_base_url}/fp-tiler"

# ports
fp_tiler_port=8080
fp_tasks_port=8081
fp_web_port=3002
tessera_port=8082
omk_server_port=3210
posm_admin_port=3211
osm_web_port=9000
cgimap_port=54321
clusterodm_port=3000
nodeodm_port=3001
webodm_port=8000

# web
# auth=true # uncomment this to enable web authentication
auth_user=POSM
auth_password=awesomeposm
# change this to 'true' to display admin entries in the POSM admin sidebar
posm_show_admin=false

# field papers
fp_secret_key_base=redacted
fp_mapzen_search_key=redacted

# osm
osm_posm_user="POSM"
osm_posm_description="Portable OpenStreetMap"

# webodm
webodm_user="POSM"
webodm_password="awesomeposm"
webodm_webapp_digest="sha256:417beb021da272635c0004f8107ef42c214c624ad9d3411bebf1f241489a4667"
webodm_nodeodm_digest="sha256:ae2345df2e4f7756e208f7b0717c6b9b95fb3a67612fa84295cdc6b4ba985eaf"
webodm_clusterodm_digest="sha256:62e5a2073ee84adf6ee86e8744f2c34d5c70ae77ce6c7ce21e359703cb2d3fdb"

# databases
fp_pg_owner="fieldpapers"
fp_pg_pass="fieldpapers"
fp_pg_dbname="fieldpapers_${posm_env}"
osm_pg_owner="osm"
osm_pg_pass="openstreetmap"
osm_pg_dbname="osm"
osm_carto_pg_dbname="gis"
osm_carto_pg_temp_dbname="gis_temp"
osm_carto_pg_owner="gis"
osm_carto_pg_users="root fp omk"
osm_carto_pg_pass="openstreetmap"
webodm_pg_owner="webodm"
webodm_pg_pass="webodm"
webodm_pg_dbname="webodm"

# tile styles [posm, osm]
carto_styles="posm"
